server:
  port: 8080
  servlet:
    context-path: /education
spring:
  application:
    name: education
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates
    cache: false
    encoding: UTF-8