server:
  port: 8080
  servlet:
    context-path: /education
spring:
  application:
    name: education
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates
    cache: false
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/education
    data-username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver